### ISSUE TITLE
problems with the implementation of pollfish

### ISSUE THREAD

**Issue by Krypto-Manager** [pollfish/unity-plugin-pollfish#2]
Unfortunately I have problems with the implementation of pollfish.
I have proceeded as in the description.
But neither the DemoScene nor the function I created works!
I initialize pollfish and then call Pollfish.ShowPollfish by button.
There something seems to go wrong.
In the editor I get the error:

NullReferenceException: Object reference not set to an instance of an object
Pollfish.ShowPollfish () (at Assets/Plugins/Pollfish/Pollfish.cs:217)

In Android Phone the demo is not displayed correctly after I press Show!
Any idea what the problem could be?
Is there maybe a dev forum?

**Comment by kaspanvo** [comment]
Hello @Krypto-Manager there are two important things around the Android version of the Unity plugin:

1) Pollfish Unity plugin does not run on Editor (so that explains the first exception you mentioned)
2) For having issues on the android phone can you provide more info? Did you run the google play services resolver first prior deploying?

Please let us know on the above.
